/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CALCULATORS;

/**
 *
 * @author mdu
 */
public class CAL extends javax.swing.JFrame {

    /**
     * Creates new form CAL
     */
        double first;
        double second;
        double results;
        String operation;
        String answers;
    public CAL() {
        initComponents();
        setSize(416,500);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        answer = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        perce = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        divi = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        plusminus = new javax.swing.JButton();
        equal = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");
        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 65));

        answer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        answer.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 435));
        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 1, 1));

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("CE");
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clear.setHideActionText(true);
        clear.setMaximumSize(new java.awt.Dimension(30, 40));
        clear.setMinimumSize(new java.awt.Dimension(40, 40));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setText("C");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancel.setHideActionText(true);
        cancel.setMaximumSize(new java.awt.Dimension(30, 40));
        cancel.setMinimumSize(new java.awt.Dimension(40, 40));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);

        perce.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        perce.setText("%");
        perce.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        perce.setHideActionText(true);
        perce.setMaximumSize(new java.awt.Dimension(30, 40));
        perce.setMinimumSize(new java.awt.Dimension(40, 40));
        jPanel2.add(perce);

        plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plus.setText("+");
        plus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plus.setHideActionText(true);
        plus.setMaximumSize(new java.awt.Dimension(30, 40));
        plus.setMinimumSize(new java.awt.Dimension(40, 40));
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        jPanel2.add(plus);

        seven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seven.setText("7");
        seven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        seven.setHideActionText(true);
        seven.setMaximumSize(new java.awt.Dimension(30, 40));
        seven.setMinimumSize(new java.awt.Dimension(40, 40));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel2.add(seven);

        eight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eight.setText("8");
        eight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eight.setHideActionText(true);
        eight.setMaximumSize(new java.awt.Dimension(30, 40));
        eight.setMinimumSize(new java.awt.Dimension(40, 40));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel2.add(eight);

        nine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nine.setText("9");
        nine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nine.setHideActionText(true);
        nine.setMaximumSize(new java.awt.Dimension(30, 40));
        nine.setMinimumSize(new java.awt.Dimension(40, 40));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel2.add(nine);

        subtract.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subtract.setText("-");
        subtract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subtract.setHideActionText(true);
        subtract.setMaximumSize(new java.awt.Dimension(30, 40));
        subtract.setMinimumSize(new java.awt.Dimension(40, 40));
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractActionPerformed(evt);
            }
        });
        jPanel2.add(subtract);

        four.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        four.setText("4");
        four.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        four.setHideActionText(true);
        four.setMaximumSize(new java.awt.Dimension(30, 40));
        four.setMinimumSize(new java.awt.Dimension(40, 40));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel2.add(four);

        five.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        five.setText("5");
        five.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        five.setHideActionText(true);
        five.setMaximumSize(new java.awt.Dimension(30, 40));
        five.setMinimumSize(new java.awt.Dimension(40, 40));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel2.add(five);

        six.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        six.setText("6");
        six.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        six.setHideActionText(true);
        six.setMaximumSize(new java.awt.Dimension(30, 40));
        six.setMinimumSize(new java.awt.Dimension(40, 40));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel2.add(six);

        multi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multi.setText("*");
        multi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        multi.setHideActionText(true);
        multi.setMaximumSize(new java.awt.Dimension(30, 40));
        multi.setMinimumSize(new java.awt.Dimension(40, 40));
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        jPanel2.add(multi);

        one.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        one.setText("1");
        one.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        one.setHideActionText(true);
        one.setMaximumSize(new java.awt.Dimension(30, 40));
        one.setMinimumSize(new java.awt.Dimension(40, 40));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel2.add(one);

        two.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        two.setText("2");
        two.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        two.setHideActionText(true);
        two.setMaximumSize(new java.awt.Dimension(30, 40));
        two.setMinimumSize(new java.awt.Dimension(40, 40));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel2.add(two);

        three.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        three.setText("3");
        three.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        three.setHideActionText(true);
        three.setMaximumSize(new java.awt.Dimension(30, 40));
        three.setMinimumSize(new java.awt.Dimension(40, 40));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel2.add(three);

        divi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divi.setText("/");
        divi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        divi.setHideActionText(true);
        divi.setMaximumSize(new java.awt.Dimension(30, 40));
        divi.setMinimumSize(new java.awt.Dimension(40, 40));
        divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diviActionPerformed(evt);
            }
        });
        jPanel2.add(divi);

        zero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zero.setText("0");
        zero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        zero.setHideActionText(true);
        zero.setMaximumSize(new java.awt.Dimension(30, 40));
        zero.setMinimumSize(new java.awt.Dimension(40, 40));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel2.add(zero);

        dot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dot.setText(".");
        dot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dot.setHideActionText(true);
        dot.setMaximumSize(new java.awt.Dimension(30, 40));
        dot.setMinimumSize(new java.awt.Dimension(40, 40));
        jPanel2.add(dot);

        plusminus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusminus.setText("+/-");
        plusminus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plusminus.setHideActionText(true);
        plusminus.setMaximumSize(new java.awt.Dimension(30, 40));
        plusminus.setMinimumSize(new java.awt.Dimension(40, 40));
        plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusActionPerformed(evt);
            }
        });
        jPanel2.add(plusminus);

        equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equal.setText("=");
        equal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        equal.setHideActionText(true);
        equal.setMaximumSize(new java.awt.Dimension(30, 40));
        equal.setMinimumSize(new java.awt.Dimension(40, 40));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel2.add(equal);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        //set to the text field
        String sev=answer.getText()+zero.getText();
        answer.setText(sev);
    }//GEN-LAST:event_zeroActionPerformed

    private void diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diviActionPerformed
        //addition
        first=Double.parseDouble(answer.getText());
        answer.setText("");
        operation="+";
    }//GEN-LAST:event_diviActionPerformed

    private void subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractActionPerformed
         //subtraction
        first=Double.parseDouble(answer.getText());
        answer.setText("");
        operation="-";
    }//GEN-LAST:event_subtractActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        //set to the text field
        String sev=answer.getText()+seven.getText();
        answer.setText(sev);
    }//GEN-LAST:event_sevenActionPerformed

    private void plusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusminusActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
      //clear the anserfield
      answer.setText(" ");
      
    }//GEN-LAST:event_clearActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
       //set to the text field
        String sev=answer.getText()+eight.getText();
        answer.setText(sev);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        //set to the text field
        String sev=answer.getText()+nine.getText();
        answer.setText(sev);
    }//GEN-LAST:event_nineActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        //set to the text field
        String sev=answer.getText()+four.getText();
        answer.setText(sev);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        //set to the text field
        String sev=answer.getText()+five.getText();
        answer.setText(sev);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        //set to the text field
        String sev=answer.getText()+six.getText();
        answer.setText(sev);
    }//GEN-LAST:event_sixActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
       //set to the text field
        String sev=answer.getText()+three.getText();
        answer.setText(sev); // TODO add your handling code here:
    }//GEN-LAST:event_threeActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        //set to the text field
        String sev=answer.getText()+two.getText();
        answer.setText(sev);
    }//GEN-LAST:event_twoActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        //set to the text field
        String sev=answer.getText()+one.getText();
        answer.setText(sev);// TODO add your handling code here:
    }//GEN-LAST:event_oneActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
       //addition
        first=Double.parseDouble(answer.getText());
        answer.setText("");
        operation="+";
    }//GEN-LAST:event_plusActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
          
          if(answer.getText().length()>0) {
          StringBuilder builder=new StringBuilder(answer.getText());
          builder.deleteCharAt(answer.getText().length()-1);
          answer.setText(builder.toString());
        }
    }//GEN-LAST:event_cancelActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
       //addition
        first=Double.parseDouble(answer.getText());
        answer.setText("");
        operation="*";
    }//GEN-LAST:event_multiActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
       String answe;
       second=Double.parseDouble(answer.getText());
        switch(operation){
                case "+":
                    results=first+second;
                    answe=String.format("%.2f", results);
                    answer.setText(answe);
                    break;
                case "-":
                    results=first-second;
                    answe=String.format("%.2f", results);
                    answer.setText(answe);
                    break;
                case "*":
                    results=first*second;
                    answe=String.format("%.2f", results);
                    answer.setText(answe);
                    break;
                case "/":
                    results=first/second;
                    answe=String.format("%.2f", results);
                    answer.setText(answe);
                    break;
        }
    }//GEN-LAST:event_equalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JButton divi;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton multi;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton perce;
    private javax.swing.JButton plus;
    private javax.swing.JButton plusminus;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton subtract;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
